
http://localhost:3000/api/rental

### Get all rentals
http://localhost:3000/api/rentalImages

### images
POST http://localhost:3000/api/1
content-type: application/json



###
GET http://localhost:3000/api/1


###
POST http://localhost:3000/api/rentalImages
content-type: application/json

{
  "property_id": 1,
  "image_url": "https://images.pexels.com/photos/2109493/pexels-photo-2109493.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

###
GET http://localhost:3000/api/
