
http://localhost:3000/api/rental

### Get all rentals
http://localhost:3000/api/rentalImages

### images
POST http://localhost:3000/api/1
content-type: application/json



###
GET http://localhost:3000/api/1


###
PUT http://localhost:3000/api/porperty/2/images/10
content-type: application/json

{
  "property_id": 2,
  "image_url": "https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/advisor/wp-content/uploads/2021/08/download-11.jpg"
}
